src/apps/product/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from src.apps.product import views

urlpatterns = [
    url(r'^add/$', views.ProductCreateView.as_view(), name='add'),
    url(r'^$', views.ProductsListView.as_view(), name='list'),
    url(r'^(?P<slug>[-\w]+)/$', views.ProductDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[-\w]+)/edit/$', views.ProductUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', views.ProductDeleteView.as_view(), name='delete'),
    url(r'^(?P<slug>[-\w]+)/like/$', views.LikeView.as_view()),
    url(r'^(?P<slug>[-\w]+)/comment/$', views.CommentView.as_view(), name='comment'),
    url(r'^(?P<slug>[-\w]+)/comments/last/$', views.CommentView.as_view()),
]

src/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from allauth.account import views
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^signup/$', views.signup, name='account_signup'),
    url(r'^login/$', views.login, name='account_login'),
    url(r'^logout/$', views.logout, name='account_logout'),
    url(r'^products/', include('src.apps.product.urls', namespace='products'))
]

src/apps/product/forms.py
from django import forms
from model_utils import Choices

from src.apps.product.models import ProductModel, CommentModel


class FilterForm(forms.Form):
    FILTER_CHOICE = Choices(
        ('', 'Select one...'),
        ('Like', [('like', 'Like Ascending',), ('-like', 'Like Descending',)]),
        ('Price', [('price', 'Price Ascending',), ('-price', 'Price Descending',)]),
        ('Created', [('created', 'Created Ascending'), ('-created', 'Created Descending',)])
    )

    filter = forms.ChoiceField(
        label='Filter by: ',
        choices=FILTER_CHOICE,
        required=False,
        widget=forms.Select(
            attrs={
                'class': 'c-select'
            })
    )


class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductModel
        exclude = ('user', 'slug',)
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Name',
                    'required': True,
                },
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'cols': 50,
                    'row': 5,
                    'placeholder': 'Description',
                    'required': True,
                },
            ),
            'price': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'type': 'number',
                    'step': '0.01',
                    'placeholder': 'Price',
                    'required': True,
                },
            ),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        fields = ('comment',)
        widgets = {
            'comment': forms.Textarea(
                attrs={
                    'id': 'comment-text',
                    'class': 'form-control',
                    'cols': 50,
                    'row': 3,
                    'placeholder': 'Body of comment',
                    'required': True,
                },
            )
        }

src/core/forms.py
from allauth.account.forms import LoginForm, SignupForm
from django import forms
from django.core import validators


class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username',
            'required': True,
        })
        self.fields['password'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'required': True,
        })
        self.fields['remember'].widget = forms.CheckboxInput(attrs={
            'class': 'checkbox',
        })


class CustomSignupForm(SignupForm):
    username = forms.CharField(label='Username',
                               validators=[
                                   validators.MinLengthValidator(limit_value=4,
                                                                 message='Nickname length should be more \
                                                                                 than 3 characters'),
                               ],
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Username',
                                   'required': True,
                               }))
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Password',
                                    'required': True,
                                }))
    password2 = forms.CharField(label='Password (again)',
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Password (again)',
                                    'required': True,
                                }))

src/apps/product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import re

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView, DetailView
from django.views.generic import UpdateView
from pure_pagination import PaginationMixin

from src.apps.product.forms import FilterForm, ProductForm, CommentForm
from src.apps.product.models import ProductModel, LikeModel, CommentModel


class ProductsListView(PaginationMixin, ListView):
    model = ProductModel
    template_name = 'product/products.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        queryset = super(ProductsListView, self).get_queryset().select_related('user').annotate(
            like_total=Count('like'))
        if 'filter' in self.request.GET:
            select = self.request.GET['filter']
            if select != '' and select in filter(None, FilterForm.FILTER_CHOICE._db_values):
                return queryset.order_by(select)
        else:
            return queryset
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['filters'] = FilterForm(self.request.GET)
        return context


class ProductDetailView(DetailView):
    model = ProductModel
    queryset = ProductModel.objects.select_related('user').annotate(like_total=Count('like'))
    template_name = 'product/product.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['comments'] = CommentModel.objects.select_related('user', 'product').filter(
            product=self.object,
            created__gte=datetime.datetime.now() - datetime.timedelta(days=1)
        ).order_by('-created')
        context['form'] = CommentForm()
        return context


class DispatchMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            if 'slug' in kwargs:
                product = get_object_or_404(ProductModel, slug=kwargs.get('slug'))
                if product.user != request.user:
                    messages.add_message(request, messages.WARNING, 'You can not do this action')
                    return redirect(reverse('products:detail', args=(kwargs.get('slug'),)))
        return super(DispatchMixin, self).dispatch(request, *args, **kwargs)


class ProductCreateUpdateMixin(DispatchMixin):
    form_class = ProductForm
    template_name = 'product/form.html'

    def get_success_url(self, **kwargs):
        return reverse('products:detail', kwargs={
            'slug': kwargs.get('slug')
        })

    def post(self, request, *args, **kwargs):
        request.POST = request.POST.copy()
        if 'name' in request.POST:
            request.POST['name'] = request.POST['name'].capitalize()
        return super(ProductCreateUpdateMixin, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form = form.save(commit=False)
        form.user = self.request.user
        form.name = form.name
        form.description = form.description.capitalize()
        form.slug = re.sub("^\s+|\n|\r|\s+$", '', form.name.lower()).replace(' ', '-')
        form.save()
        return redirect(self.get_success_url(slug=form.slug))


class ProductCreateView(ProductCreateUpdateMixin, CreateView):
    def get_success_url(self, **kwargs):
        messages.add_message(self.request, messages.INFO,
                             'Product {} successfully added'.format(self.request.POST['name']))
        return super(ProductCreateView, self).get_success_url(**kwargs)


class ProductUpdateView(ProductCreateUpdateMixin, UpdateView):
    model = ProductModel
    context_object_name = 'product'

    def get_success_url(self, **kwargs):
        messages.add_message(self.request, messages.INFO,
                             'Product {} successfully changed'.format(self.object.name))
        return super(ProductUpdateView, self).get_success_url(**kwargs)


class ProductDeleteView(DispatchMixin, DeleteView):
    model = ProductModel
    context_object_name = 'product'
    template_name = 'product/delete.html'
    success_url = '/products/'

    def get_success_url(self, **kwargs):
        messages.add_message(self.request, messages.INFO,
                             'Product {} successfully deleted'.format(self.object.name))
        return super(ProductDeleteView, self).get_success_url()


class LikeView(LoginRequiredMixin, View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            if request.is_ajax():
                return JsonResponse({'message': 'To perform this action, you must be logged.'}, status=403)
            else:
                return self.get(request, *args, **kwargs)
        return super(LikeView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return redirect(reverse('products:detail', kwargs={'slug': self.kwargs['slug']}))

    def post(self, request, **kwargs):
        if request.is_ajax():
            product = get_object_or_404(ProductModel.objects, slug=kwargs.get('slug'))
            try:
                LikeModel.objects.get(user=request.user, product=product).delete()
                msg = 'Like deleted'
                status = 200
            except LikeModel.DoesNotExist:
                LikeModel.objects.create(user=request.user, product=product)
                msg = 'Like added'
                status = 201
            return JsonResponse({'message': msg, 'like_count': product.like.count()}, status=status)


class CommentView(CreateView):
    model = CommentModel
    form_class = CommentForm
    context_object_name = 'comment'
    template_name = 'product/product.html'

    comment_html = '''<div class="media" data-id={comment_id}>
                            <a class="media-left" href="#">
                                <img class="media-object" src="http://placehold.it/50x50" alt="User Photo">
                            </a>
                        <div class="media-body">
                            <h4 class="media-heading">{author}</h4>
                            <p>{comment}</p>
                        </div>
                        <div class="media-footer">
                            <p>{created}</p>
                        </div>
                    </div>'''

    def get(self, request, *args, **kwargs):
        return redirect(reverse('products:detail', kwargs={'slug': kwargs['slug']}))

    def get_success_url(self):
        messages.add_message(self.request, messages.INFO,
                             'Comment successfully added')
        return reverse('products:detail', kwargs={'slug': self.kwargs['slug']})

    def post(self, request, *args, **kwargs):
        if 'last' in self.request.path and 'id' in self.request.POST:
            response_data = dict()
            html = ''
            response_data['disabled'] = False
            if self.request.POST['id'] == '0':
                comments = CommentModel.objects.prefetch_related('user', 'product').filter(
                    product_id=self.kwargs['slug']).order_by('-created')[:5]
                if comments.count() < 5:
                    response_data['disabled'] = True
            else:
                date = CommentModel.objects.get(id=int(self.request.POST['id'])).created
                comments = CommentModel.objects.prefetch_related('user', 'product').filter(
                    product_id=self.kwargs['slug'], created__lt=date).order_by('-created')[:5]
                if comments.count() < 5:
                    response_data['disabled'] = True
            for comment in comments:
                author = 'Anonymous'
                created = comment.created.strftime("%B %d, %Y, %-I:%M %p")
                if comment.user is not None:
                    author = comment.user.username
                html += ''.join(self.comment_html.format(comment_id=comment.id,
                                                         author=author,
                                                         comment=comment.comment,
                                                         created=created))
            response_data['html'] = html
            return JsonResponse(response_data, status=200)
        return super(CommentView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        response_data = dict()

        form = form.save(commit=False)
        product = ProductModel.objects.get(slug=self.kwargs.get('slug'))
        if self.request.user.is_anonymous():
            form.user = None
            author = 'Anonymous'
        else:
            form.user = self.request.user
            author = form.user.username
        form.product = product
        form.save()
        if self.request.is_ajax():
            comment_id = CommentModel.objects.all().order_by('created').last().id
            comment = form.comment
            created = form.created.strftime('%B %d, %Y, %I:%M %p')
            response_data['message'] = 'Your comment has successfully added'
            response_data['html'] = self.comment_html.format(comment_id=comment_id,
                                                             author=author,
                                                             comment=comment,
                                                             created=created)
            return JsonResponse(response_data, status=201)
        return super(CommentView, self).form_valid(form)

src/templates/product/comment.html
{% load i18n %}
<section class="p-a-1">
    <h2 class="text-md-center">{% trans 'Comments' %}:</h2>
    {% if form.errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-warning" role="alert">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <form id="comment-form" method="post" action="{% url 'products:comment' product.slug %}" class="row text-md-center">
        {% csrf_token %}
        {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
        {{ form }}
        <div class="clearfix"></div>
        <br>
        <button id="comment-submit" class="btn btn-primary" disabled>{% trans 'Add comment' %}</button>
    </form>
    {% for comment in comments %}
        <div class="media" data-id="{{ comment.id }}">
            <a class="media-left" href="#">
                <img class="media-object" src="http://placehold.it/50x50" alt="User Photo">
            </a>
            <div class="media-body">
                <h4 class="media-heading">
                    {% if comment.user.username %}
                        {{ comment.user.username }}
                    {% else %}
                        Anonymous
                    {% endif %}
                </h4>
                <p>{{ comment.comment }}</p>
            </div>
            <div class="media-footer">
                <p>{{ comment.created|date:"F d, Y," }} {{ comment.created|time:"H:i A" }}</p>
            </div>
        </div>
    {% empty %}
        <p id="no-comments">{% trans 'No comments' %}</p>
    {% endfor %}
    <div class="text-md-center">
        <button class="btn btn-info" id="last-comments">Show last 5 comments</button>
    </div>
</section>

src/templates/product/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {% trans 'Delete product' %} - {{ product.name }}
{% endblock %}
{% block content %}
    <article class="p-a-1">
        <header>
            <h2 class="text-md-center">{% trans 'Delete product' %} {{ product.name }}</h2>
        </header>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <p class="text-danger text-md-center">
            {% trans 'Are you sure you want to delete' %} <strong>{{ product.name }}</strong>
        </p>
        <form action="" method="post" class="text-md-center">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">{% trans 'Delete' %}</button>
            <a href="{% url 'products:detail' product.slug %}"
               class="btn btn-success">{% trans 'Cancel' %}</a>
        </form>
    </article>
{% endblock %}

src/templates/product/form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {% if not product %}
        {% trans 'Add new Product' %}
    {% else %}
        {% trans 'Edit' %} {{ product.name }}
    {% endif %}
{% endblock %}
{% block content %}
    <article class="p-a-1">
        <header class="m-b-3">
            <h2 class="text-md-center">
                {% if not product %}
                    {% trans 'Add new Product' %}
                {% else %}
                    {% trans 'Edit' %} {{ product.name }}
                {% endif %}
            </h2>
        </header>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-warning" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form class="col-md-4 col-md-offset-4 m-b-1" method="post">
            {% csrf_token %}
            {% for field in form %}
                <fieldset class="form-group {% if field.errors %}has-danger{% endif %}">
                    <label for="{{ field.name }}">{{ field.label }}:</label>
                    {% for error in field.errors %}
                        <div role="alert">
                            <strong class="alert-danger m-l-1">{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                    <div class="clearfix"></div>
                    {{ field }}
                </fieldset>
            {% endfor %}
            <button class="btn btn-primary" type="submit">
                {% if not product %}
                    {% trans 'Add product' %} &raquo;
                {% else %}
                    {% trans 'Save' %} &raquo;
                {% endif %}
            </button>
        </form>
        <div class="clearfix"></div>
    </article>
{% endblock %}

src/templates/product/product.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <article class="m-t-1">
        <div class="card">
            {% if product.user == request.user %}
                <div class="card-header pull-right">
                    <div class="btn-group" role="group">
                        <a href="{% url 'products:edit' product.slug %}"
                           class="btn btn-primary">{% trans 'Edit product' %}</a>
                        <a href="{% url 'products:delete' product.slug %}"
                           class="btn btn-danger">{% trans 'Delete product' %}</a>
                    </div>
                </div>
            {% endif %}
            {% if user.is_authenticated %}
                <div class="card-header pull-left">
                    <div class="btn-group" role="group">
                        <a href="{% url 'products:add' %}" class="btn btn-success">{% trans 'Add new product' %}</a>
                    </div>
                </div>
            {% endif %}
            <div class="clearfix"></div>
            <div class="card-block">
                <h2 class="card-title text-md-center">{{ product.name }}</h2>
                <p class="card-text lead indent">{{ product.description }}</div>
            <div class="card-footer">
                <div class="pull-right">
                    <div id="like" {% if user.is_authenticated %}class="pointer"{% endif %}>
                        <span class="label label-success">
                            Like <i class="fa fa-heart"
                                    aria-hidden="true"></i> <samp>{{ product.like_total }}</samp>
                        </span>
                    </div>
                    <span class="label label-info">{% trans 'Price:' %} {{ product.price }} <i class="fa fa-usd"
                                                                                               aria-hidden="true"></i></span>
                </div>
                <div class="pull-left">
                    <span class="label label-pill label-default">
                        <i class="fa fa-user" aria-hidden="true">{% trans 'Author:' %} {{ product.user }}</i>
                    </span>
                    <br>
                    <span class="label label-pill label-default">
                        <i class="fa fa-calendar"
                           aria-hidden="true">{% trans 'Create:' %} {{ product.created|date }}</i>
                    </span>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        {% include 'product/comment.html' %}
    </article>
{% endblock %}
{% block extra_scripts %}
    {% if user.is_authenticated %}
        <script src="{% static 'js/like.js' %}"></script>
    {% endif %}
    <script src="{% static 'js/comment.js' %}"></script>
{% endblock %}

src/templates/product/products.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'List of Products' %}
{% endblock %}
{% block content %}
    <article class="m-t-1">
        <header class="text-md-center">
            <h2 class="text-primary">{% trans 'List of products:' %}</h2>
        </header>
        <aside class="p-a-1">
            <div class="pull-right">
                {% if user.is_authenticated %}
                    <a href="{% url 'products:add' %}" class="btn btn-primary">{% trans 'Add product' %}</a>
                {% else %}
                    <p class="card-text text-md-center">{% trans 'You need to be logged in, to add the product.' %}</p>
                {% endif %}
            </div>
            {% if products %}
                <div class="pull-left">
                    <form class="form form-horizontal" method="get" action="{% url 'products:list' %}" id="filter_form">
                        {% for filter in filters %}
                            <fieldset class="form-group">
                                <label class="control-label" for="{{ filter.name }}">{{ filter.label }}</label>
                                {% autoescape off %}
                                    {{ filter }}
                                {% endautoescape %}
                            </fieldset>
                        {% endfor %}
                    </form>
                </div>
            {% endif %}
            <div class="clearfix"></div>
        </aside>
        {% for product in products %}
            <div class="list-group">
                <a href="{{ product.get_absolute_url }}" class="list-group-item list-group-item-info">
                    <h4 class="list-group-item-heading">{{ product.name }}</h4>
                    <p class="list-group-item-text">{{ product.description|truncatewords:50 }}</p>
                    <div class="pull-left">
                    <span class="label label-info">
                        Price: {{ product.price }}
                        <i class="fa fa-usd" aria-hidden="true"></i>
                    </span>
                        <br>
                        <span class="label label-success">
                        Like <i class="fa fa-heart" aria-hidden="true"></i> {{ product.like_total }}
                    </span>
                    </div>
                    <div class="pull-right">
                        <span class="label label-pill label-default">{% trans 'Author:' %} {{ product.user }}</span>
                        <br>
                        <span class="label label-pill label-default">{% trans 'Create:' %} {{ product.created|date }}</span>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
        {% empty %}
            <div class="card card-block text-md-center">
                <h4 class="card-title">{% trans 'No have any products.' %}</h4>
            </div>
        {% endfor %}
        {% if is_paginated %}
            {% include 'blocks/_pagination.html' %}
        {% endif %}
    </article>
{% endblock %}
{% block extra_scripts %}
    <script src="{% static 'js/filter.js' %}"></script>
{% endblock %}